/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BuilderProject.app;

import BuilderProject.list.LinkedList;

import static BuilderProject.utilities.StringUtils.join;
import static BuilderProject.utilities.StringUtils.split;
import static BuilderProject.app.MessageUtils.getMessage;

import guet.yongyu.Builder.Builder;
import guet.yongyu.Builder.MixedBuilder;
import guet.yongyu.Factory.BuilderFactory;
import guet.yongyu.Impl.Project;
import guet.yongyu.Specify.*;
import guet.yongyu.Utils.TextFile;
import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        Builder builder = null;
        try {
            builder = BuilderFactory.getInstance().getProjectBuilder("c");
            System.out.println(builder.getClass());
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }
        Project project = new CProject("E:\\codeblockProject\\BuilderTest","c");
        TextFile input = new TextFile("E:\\IdealProject\\CTest\\input.txt");
        builder.run(project);
    }
}
