/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BuilderProject.app;

import BuilderProject.list.LinkedList;

import static BuilderProject.utilities.StringUtils.join;
import static BuilderProject.utilities.StringUtils.split;
import static BuilderProject.app.MessageUtils.getMessage;

import guet.yongyu.Builder.Builder;
import guet.yongyu.Builder.MixedBuilder;
import guet.yongyu.Impl.Project;
import guet.yongyu.Specify.CProject;
import guet.yongyu.Specify.GccCompiler;
import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        Project project = new CProject("E:\\ext","c");
        project.getOutputDir();
    }
}
